language: elixir
elixir:
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - 1.4.0
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.4.4
  - 1.4.5
otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 18.3
  - 19.0
  - 19.1
  - 19.2
  - 19.3
  - 20.0
matrix:
  exclude:
    - elixir: 1.3.0
      otp_release: 20.0
    - elixir: 1.3.1
      otp_release: 20.0
    - elixir: 1.3.2
      otp_release: 20.0
    - elixir: 1.3.3
      otp_release: 20.0
    - elixir: 1.3.4
      otp_release: 20.0
    - elixir: 1.4.0
      otp_release: 20.0
    - elixir: 1.4.1
      otp_release: 20.0
    - elixir: 1.4.2
      otp_release: 20.0
    - elixir: 1.4.3
      otp_release: 20.0
    - elixir: 1.4.4
      otp_release: 20.0

